import type { Asset } from '../types/api'

// Always "just now" so assetTelemetryFreshness() always returns 'fresh'
const MOCK_UPDATED_AT = new Date(Date.now() - 90_000).toISOString() // 90s ago

export const MOCK_ASSETS: Asset[] = [
  {
    id: 'asset-1',
    assetCode: 'HP-TEN-001',
    name: 'Wärmepumpe Kiel Hafen',
    assetType: 'heat_pump',
    ownerName: 'Stadtwerke Kiel',
    status: 'active',
    controllable: true,
    nominalPowerKw: 45,
    availableFlexUpKw: 38,
    availableFlexDownKw: 18,
    availableEnergyKwh: 85,
    city: 'Kiel',
    postalCode: '24103',
    federalState: 'Schleswig-Holstein',
    latitude: 54.323,
    longitude: 10.139,
    gridNode: 'KI-110-001',
    feederName: 'KI-MS-01A',
    balancingGroup: 'BG-FSP-NORD-01',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'sh-netz',
    vnbPlanningRegion: 'nord-west',
    melo: 'DE00056789012345678901234567890123',
    flexAssetIds: ['asset-1-flex'],
    shovelerSiteId: 'site-asset-1',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-2',
    assetCode: 'BAT-TEN-002',
    name: 'Gewerbebatterie Bremen-Nord',
    assetType: 'ci_battery',
    ownerName: 'EWE Energielösungen',
    status: 'active',
    controllable: true,
    nominalPowerKw: 95,
    availableFlexUpKw: 88,
    availableFlexDownKw: 90,
    availableEnergyKwh: 190,
    city: 'Bremen',
    postalCode: '28217',
    federalState: 'Bremen',
    latitude: 53.118,
    longitude: 8.788,
    gridNode: 'HB-110-003',
    feederName: 'HB-MS-02A',
    balancingGroup: 'BG-FSP-NORD-01',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'ewe-netz',
    vnbPlanningRegion: 'nord-west',
    melo: 'DE00012345678901234567890123456789',
    flexAssetIds: ['asset-2-bat'],
    shovelerSiteId: 'site-asset-2',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-3',
    assetCode: 'HP-TEN-003',
    name: 'Wärmepumpe Heide Zentrum',
    assetType: 'heat_pump',
    ownerName: 'Stadtwerke Heide',
    status: 'active',
    controllable: true,
    nominalPowerKw: 30,
    availableFlexUpKw: 25,
    availableFlexDownKw: 12,
    availableEnergyKwh: 55,
    city: 'Heide',
    postalCode: '25746',
    federalState: 'Schleswig-Holstein',
    latitude: 54.195,
    longitude: 9.097,
    gridNode: 'HEI-20-001',
    feederName: 'HEI-NS-01A',
    balancingGroup: 'BG-FSP-NORD-01',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'sw-heide',
    vnbPlanningRegion: 'nord-west',
    melo: null,
    flexAssetIds: ['asset-3-flex'],
    shovelerSiteId: 'site-asset-3',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-4',
    assetCode: 'BAT-TEN-004',
    name: 'Hausbatterie Oldenburg-West',
    assetType: 'home_battery',
    ownerName: 'Privat Müller',
    status: 'active',
    controllable: true,
    nominalPowerKw: 10,
    availableFlexUpKw: 8,
    availableFlexDownKw: 9,
    availableEnergyKwh: 20,
    city: 'Oldenburg',
    postalCode: '26123',
    federalState: 'Niedersachsen',
    latitude: 53.143,
    longitude: 8.214,
    gridNode: 'OL-20-007',
    feederName: 'OL-NS-04B',
    balancingGroup: 'BG-FSP-NORD-02',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'ewe-netz',
    vnbPlanningRegion: 'nord-west',
    melo: null,
    flexAssetIds: ['asset-4-bat', 'asset-4-pv'],
    shovelerSiteId: 'site-asset-4',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-5',
    assetCode: 'HP-TEN-005',
    name: 'Wärmepumpe Lüneburg Bahnhof',
    assetType: 'heat_pump',
    ownerName: 'Wohnungsbau Lüneburg',
    status: 'active',
    controllable: true,
    nominalPowerKw: 55,
    availableFlexUpKw: 48,
    availableFlexDownKw: 22,
    availableEnergyKwh: 110,
    city: 'Lüneburg',
    postalCode: '21335',
    federalState: 'Niedersachsen',
    latitude: 53.249,
    longitude: 10.406,
    gridNode: 'LG-110-002',
    feederName: 'LG-MS-03A',
    balancingGroup: 'BG-FSP-NORD-01',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'ewe-netz',
    vnbPlanningRegion: 'nord-west',
    melo: 'DE00098765432109876543210987654321',
    flexAssetIds: ['asset-5-flex'],
    shovelerSiteId: 'site-asset-5',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-6',
    assetCode: 'BAT-TEN-006',
    name: 'Industriebatterie Hannover-Ost',
    assetType: 'ci_battery',
    ownerName: 'ProLogis Hannover',
    status: 'active',
    controllable: true,
    nominalPowerKw: 90,
    availableFlexUpKw: 83,
    availableFlexDownKw: 86,
    availableEnergyKwh: 180,
    city: 'Hannover',
    postalCode: '30559',
    federalState: 'Niedersachsen',
    latitude: 52.374,
    longitude: 9.858,
    gridNode: 'H-380-001',
    feederName: 'H-HS-01A',
    balancingGroup: 'BG-FSP-NORD-02',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'ewe-netz',
    vnbPlanningRegion: 'nord-west',
    melo: 'DE00011111111111111111111111111111',
    flexAssetIds: ['asset-6-bat'],
    shovelerSiteId: 'site-asset-6',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-7',
    assetCode: 'HP-TEN-007',
    name: 'Wärmepumpe Bremerhaven Hafen',
    assetType: 'heat_pump',
    ownerName: 'Bremerhavener Wärme GmbH',
    status: 'active',
    controllable: true,
    nominalPowerKw: 80,
    availableFlexUpKw: 70,
    availableFlexDownKw: 35,
    availableEnergyKwh: 160,
    city: 'Bremerhaven',
    postalCode: '27568',
    federalState: 'Bremen',
    latitude: 53.549,
    longitude: 8.578,
    gridNode: 'BHV-110-004',
    feederName: 'BHV-MS-02B',
    balancingGroup: 'BG-FSP-NORD-01',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'wesernetz',
    vnbPlanningRegion: 'nord-west',
    melo: null,
    flexAssetIds: ['asset-7-flex'],
    shovelerSiteId: 'site-asset-7',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-8',
    assetCode: 'BAT-TEN-008',
    name: 'PV-Batterie Augsburg Süd',
    assetType: 'pv_coupled',
    ownerName: 'SolarPark Augsburg',
    status: 'active',
    controllable: true,
    nominalPowerKw: 85,
    availableFlexUpKw: 74,
    availableFlexDownKw: 79,
    availableEnergyKwh: 170,
    city: 'Augsburg',
    postalCode: '86159',
    federalState: 'Bayern',
    latitude: 48.332,
    longitude: 10.898,
    gridNode: 'AUG-110-002',
    feederName: 'AUG-MS-04A',
    balancingGroup: 'BG-FSP-SUED-01',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'lew-verteil',
    vnbPlanningRegion: 'sued-west',
    melo: 'DE00022222222222222222222222222222',
    flexAssetIds: ['asset-8-pv', 'asset-8-bat'],
    shovelerSiteId: 'site-asset-8',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-9',
    assetCode: 'HP-TEN-009',
    name: 'Wärmepumpe Celle Altstadt',
    assetType: 'heat_pump',
    ownerName: 'Stadtwerke Celle',
    status: 'active',
    controllable: true,
    nominalPowerKw: 40,
    availableFlexUpKw: 34,
    availableFlexDownKw: 16,
    availableEnergyKwh: 75,
    city: 'Celle',
    postalCode: '29221',
    federalState: 'Niedersachsen',
    latitude: 52.625,
    longitude: 10.082,
    gridNode: 'CE-20-003',
    feederName: 'CE-NS-02A',
    balancingGroup: 'BG-FSP-NORD-02',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'ewe-netz',
    vnbPlanningRegion: 'nord-west',
    melo: null,
    flexAssetIds: ['asset-9-flex'],
    shovelerSiteId: 'site-asset-9',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-10',
    assetCode: 'BAT-TEN-010',
    name: 'Gewerbebatterie Flensburg',
    assetType: 'ci_battery',
    ownerName: 'FlensBus Energy',
    status: 'active',
    controllable: true,
    nominalPowerKw: 80,
    availableFlexUpKw: 73,
    availableFlexDownKw: 77,
    availableEnergyKwh: 160,
    city: 'Flensburg',
    postalCode: '24937',
    federalState: 'Schleswig-Holstein',
    latitude: 54.793,
    longitude: 9.434,
    gridNode: 'FL-110-001',
    feederName: 'FL-MS-01A',
    balancingGroup: 'BG-FSP-NORD-01',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'sh-netz',
    vnbPlanningRegion: 'nord-west',
    melo: 'DE00033333333333333333333333333333',
    flexAssetIds: ['asset-10-bat'],
    shovelerSiteId: 'site-asset-10',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-11',
    assetCode: 'HP-TEN-011',
    name: 'Wärmepumpe Weilheim Zentrum',
    assetType: 'heat_pump',
    ownerName: 'Stadtwerke Weilheim',
    status: 'active',
    controllable: true,
    nominalPowerKw: 35,
    availableFlexUpKw: 30,
    availableFlexDownKw: 14,
    availableEnergyKwh: 65,
    city: 'Weilheim',
    postalCode: '82362',
    federalState: 'Bayern',
    latitude: 47.839,
    longitude: 11.149,
    gridNode: 'WM-20-001',
    feederName: 'WM-NS-01A',
    balancingGroup: 'BG-FSP-SUED-01',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'sw-weilheim',
    vnbPlanningRegion: 'sued-west',
    melo: null,
    flexAssetIds: ['asset-11-flex'],
    shovelerSiteId: 'site-asset-11',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-12',
    assetCode: 'BAT-TEN-012',
    name: 'Industriebatterie Ingolstadt',
    assetType: 'ci_battery',
    ownerName: 'Audi AG Werk 1',
    status: 'active',
    controllable: true,
    nominalPowerKw: 95,
    availableFlexUpKw: 87,
    availableFlexDownKw: 90,
    availableEnergyKwh: 190,
    city: 'Ingolstadt',
    postalCode: '85057',
    federalState: 'Bayern',
    latitude: 48.763,
    longitude: 11.426,
    gridNode: 'IN-380-001',
    feederName: 'IN-HS-01A',
    balancingGroup: 'BG-FSP-SUED-01',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'lew-verteil',
    vnbPlanningRegion: 'sued-west',
    melo: 'DE00044444444444444444444444444444',
    flexAssetIds: ['asset-12-bat'],
    shovelerSiteId: 'site-asset-12',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-13',
    assetCode: 'HP-TEN-013',
    name: 'Wärmepumpe Itzehoe Nord',
    assetType: 'heat_pump',
    ownerName: 'Wohnbau Itzehoe',
    status: 'active',
    controllable: true,
    nominalPowerKw: 25,
    availableFlexUpKw: 21,
    availableFlexDownKw: 10,
    availableEnergyKwh: 48,
    city: 'Itzehoe',
    postalCode: '25524',
    federalState: 'Schleswig-Holstein',
    latitude: 53.924,
    longitude: 9.516,
    gridNode: 'IZ-20-002',
    feederName: 'IZ-NS-01A',
    balancingGroup: 'BG-FSP-NORD-01',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'sh-netz',
    vnbPlanningRegion: 'nord-west',
    melo: null,
    flexAssetIds: ['asset-13-flex'],
    shovelerSiteId: 'site-asset-13',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-14',
    assetCode: 'BAT-TEN-014',
    name: 'Hausbatterie München-Pasing',
    assetType: 'home_battery',
    ownerName: 'Privat Schmidt',
    status: 'active',
    controllable: true,
    nominalPowerKw: 12,
    availableFlexUpKw: 10,
    availableFlexDownKw: 11,
    availableEnergyKwh: 24,
    city: 'München',
    postalCode: '81241',
    federalState: 'Bayern',
    latitude: 48.148,
    longitude: 11.462,
    gridNode: 'M-20-018',
    feederName: 'M-NS-07B',
    balancingGroup: 'BG-FSP-SUED-01',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'sw-weilheim',
    vnbPlanningRegion: 'sued-west',
    melo: null,
    flexAssetIds: ['asset-14-bat', 'asset-14-pv'],
    shovelerSiteId: 'site-asset-14',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-15',
    assetCode: 'HP-TEN-015',
    name: 'Wärmepumpe Wolfsburg Mitte',
    assetType: 'heat_pump',
    ownerName: 'VW Immobilien',
    status: 'active',
    controllable: true,
    nominalPowerKw: 70,
    availableFlexUpKw: 62,
    availableFlexDownKw: 28,
    availableEnergyKwh: 140,
    city: 'Wolfsburg',
    postalCode: '38440',
    federalState: 'Niedersachsen',
    latitude: 52.423,
    longitude: 10.787,
    gridNode: 'WOB-110-003',
    feederName: 'WOB-MS-02A',
    balancingGroup: 'BG-FSP-NORD-02',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'ewe-netz',
    vnbPlanningRegion: 'nord-west',
    melo: 'DE00055555555555555555555555555555',
    flexAssetIds: ['asset-15-flex'],
    shovelerSiteId: 'site-asset-15',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-16',
    assetCode: 'BAT-TEN-016',
    name: 'Gewerbebatterie Stade Hafen',
    assetType: 'ci_battery',
    ownerName: 'Norsk Hydro Aluminium',
    status: 'active',
    controllable: true,
    nominalPowerKw: 90,
    availableFlexUpKw: 82,
    availableFlexDownKw: 85,
    availableEnergyKwh: 180,
    city: 'Stade',
    postalCode: '21682',
    federalState: 'Niedersachsen',
    latitude: 53.594,
    longitude: 9.476,
    gridNode: 'STD-380-001',
    feederName: 'STD-HS-01A',
    balancingGroup: 'BG-FSP-NORD-01',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'ewe-netz',
    vnbPlanningRegion: 'nord-west',
    melo: 'DE00066666666666666666666666666666',
    flexAssetIds: ['asset-16-bat'],
    shovelerSiteId: 'site-asset-16',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-17',
    assetCode: 'HP-TEN-017',
    name: 'Wärmepumpe Kempten Allgäu',
    assetType: 'heat_pump',
    ownerName: 'Stadtwerke Kempten',
    status: 'active',
    controllable: true,
    nominalPowerKw: 50,
    availableFlexUpKw: 44,
    availableFlexDownKw: 20,
    availableEnergyKwh: 95,
    city: 'Kempten',
    postalCode: '87435',
    federalState: 'Bayern',
    latitude: 47.726,
    longitude: 10.312,
    gridNode: 'KE-110-001',
    feederName: 'KE-MS-01A',
    balancingGroup: 'BG-FSP-SUED-01',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'lew-verteil',
    vnbPlanningRegion: 'sued-west',
    melo: null,
    flexAssetIds: ['asset-17-flex'],
    shovelerSiteId: 'site-asset-17',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-18',
    assetCode: 'BAT-TEN-018',
    name: 'PV-Batterie Rosenheim Ost',
    assetType: 'pv_coupled',
    ownerName: 'Grüne Energie Rosenheim',
    status: 'active',
    controllable: true,
    nominalPowerKw: 90,
    availableFlexUpKw: 79,
    availableFlexDownKw: 83,
    availableEnergyKwh: 180,
    city: 'Rosenheim',
    postalCode: '83022',
    federalState: 'Bayern',
    latitude: 47.857,
    longitude: 12.128,
    gridNode: 'RO-110-002',
    feederName: 'RO-MS-03A',
    balancingGroup: 'BG-FSP-SUED-01',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'lew-verteil',
    vnbPlanningRegion: 'sued-west',
    melo: 'DE00077777777777777777777777777777',
    flexAssetIds: ['asset-18-pv', 'asset-18-bat'],
    shovelerSiteId: 'site-asset-18',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-19',
    assetCode: 'HP-TEN-019',
    name: 'Wärmepumpe Braunschweig West',
    assetType: 'heat_pump',
    ownerName: 'BS Energy',
    status: 'active',
    controllable: true,
    nominalPowerKw: 65,
    availableFlexUpKw: 57,
    availableFlexDownKw: 26,
    availableEnergyKwh: 125,
    city: 'Braunschweig',
    postalCode: '38118',
    federalState: 'Niedersachsen',
    latitude: 52.265,
    longitude: 10.479,
    gridNode: 'BS-110-005',
    feederName: 'BS-MS-04A',
    balancingGroup: 'BG-FSP-NORD-02',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'ewe-netz',
    vnbPlanningRegion: 'nord-west',
    melo: null,
    flexAssetIds: ['asset-19-flex'],
    shovelerSiteId: 'site-asset-19',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
  {
    id: 'asset-20',
    assetCode: 'BAT-TEN-020',
    name: 'Gewerbebatterie Osnabrück',
    assetType: 'ci_battery',
    ownerName: 'Georgsmarienhütte GmbH',
    status: 'active',
    controllable: true,
    nominalPowerKw: 90,
    availableFlexUpKw: 83,
    availableFlexDownKw: 86,
    availableEnergyKwh: 180,
    city: 'Osnabrück',
    postalCode: '49090',
    federalState: 'Niedersachsen',
    latitude: 52.279,
    longitude: 8.043,
    gridNode: 'OS-110-003',
    feederName: 'OS-MS-02A',
    balancingGroup: 'BG-FSP-NORD-02',
    settlementRelevant: true,
    uenbRegion: 'tennet',
    vnbOperator: 'ewe-netz',
    vnbPlanningRegion: 'nord-west',
    melo: 'DE00088888888888888888888888888888',
    flexAssetIds: ['asset-20-bat'],
    shovelerSiteId: 'site-asset-20',
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: MOCK_UPDATED_AT,
    telemetryFreshnessSeconds: 300,
  },
]
